# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: Build
description: Build
author: mesopelagique
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.file }} 
    - ${{ inputs.fail-on-warning }}
branding:
  icon: 'code'
  color: 'blue'
inputs:
  file:
    description: "Path to the project file"
    required: false
  fail-on-warning:
    description: "Failed on warning"
    required: false
    default: 1
