name: release

on:
  release:
    types: [published]
    tags-ignore:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and release action
        uses: mesopelagique/build-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
          RELEASE: 1
